clean:
	rm *.out *.err *.tmp *.png || true
	rm output/*.dat output/A_values_by_order.tmp output/blaze1_chi2.tmp output/blaze2_chi2.tmp output/lc_values_by_order.tmp output/A_values_by_order.tmp output/poly_coeff_A.tmp output/poly_coeff_lc.tmp

